server:
  port: 9002
spring:
  application:
    name: nacos-provider
  cloud:
      nacos:
        discovery:
          server-addr: localhost:8848 #单机版nacos的IP
management:
  endpoints:
    web:
      exposure:
        include: '*' #暴露要监控的内容
