server:
  port: 3344

spring:
  application:
    name: config-server-center
  cloud:
    config:
      server:
        git:
          uri: https://github.com/lidagen/cloud-config.git
          ignoreLocalSshSettings: true #为了激活基于属性的SSH配置
          search-paths: ## 搜索目录
            - cloud-config
          default-label: master #读取分支


eureka:
  client:
    service-url:
      #设置与eureka交互的地址查询服务和注册服务需要依赖这个地址
      defaultZone: http://eureka7001:7001/eureka/,http://eureka7002:7002/eureka/
