server:
  port: 7002

eureka:
  # eureka自我保护关闭，保证服务不可用时剔除
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 2000
  instance:
    hostname: eureka7002
  client:
    service-url:
      #设置与eureka交互的地址查询服务和注册服务需要依赖这个地址
      defaultZone: http://eureka7001:7001/eureka/
    register-with-eureka: false
    fetch-registry: false




