server:
  port: 7002

eureka:
  instance:
    hostname: eureka7002
  client:
    service-url:
      #设置与eureka交互的地址查询服务和注册服务需要依赖这个地址
      defaultZone: http://eureka7001:7001/eureka/
    register-with-eureka: false
    fetch-registry: false




